version: '3'

services:

    postgres:
        image: postgres:13.3-alpine
        container_name: db-container
        environment:
            - POSTGRES_DB=db_teste
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - TZ=GMT
        volumes:
            - postgres-volume-db:/var/lib/postgresql/data
        ports:
            - 5432:5432

    pg_admin:
        image: dpage/pgadmin4:latest
        container_name: pg_admin
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres@local.com
            - PGADMIN_DEFAULT_PASSWORD=postgres
        ports:
            - 80:80
        depends_on:
            - postgres

volumes:
    postgres-volume-db: